language: rust
os:
  - linux
  - osx
rust:
  - stable
cache: cargo
script:
  - cargo build --verbose --all --release
  - cargo test --verbose --all --release
deploy:
  provider: bintray
  file: "./deploy/descriptor.json"
  user: maximfischuk
  skip_cleanup: false
  key:
    secure: aQ3gBLbz4iF9zCFndgwR6yc2+Ui6HsiV6pyM35j/w1oz/PQZO02Y8fDCfPvZMa5LlyheoM40W8ZzlAw0XHXoVw66IoymDD+Bobvrt16E46rVjfCeRr+91z3XaLqU4aeCoJdVU/4j73W+6ftAgI9PkQjhTC4IuVWvh15z1wzRhoKhgGJUa/MWltS2MsGym8zx7em0/4S2494vVBk6SK2o08ibjIlU4UAYj5Y4SaRMNEfiqLuAi2I+Ke1MYZpEi2dmjEnMdwsB/loBPnfLoa9kt1k/Qq2oWFArzrRLq2tX8ngDXCbIshssNIfqfoC9xXP14zfkXL0t4CIznqE8BDQcvJj9vaSY5M5Tavzm1EGE9lbzNvPyPmPRLpA2mdjMsOlmcvJCGCwcixX8s8KWOJpEnLoDG4uI9CWa1FZmVs5G0N4+5itLdmwd9aaqf0PNfPcmSwclQBBmtXzcrUVmWj5l4PCpeBfStZgMzZ75xGI4QmhVrFMrYJJ/cuhIMKvvrdYKzrjPNF7RYCtnmymkD2IeGUqE1VMW+htFfXV6hHoXW+RjtnyfPwDeE60ytWne4EKspuW55wePnlPqiGMQ2deJfDeBbBB9DOEC9Vs86ZI+XhBfFqsb6XjsGIWO9DFqs0EixHsnO5AhM2AEQZFWbIKGr6PjzIz02fdJABR10CQfjdc=
