language: rust
os:
  - linux
  - osx
rust:
  - stable
cache: cargo
script:
  - cargo build --verbose --all --release
  - cargo test --verbose --all --release
deploy:
  provider: bintray
  file: ./deploy/descriptor.json
  skip_cleanup: true
