name: Example
collect: mongodb://root:test123@localhost:27017
resources:
  - ./resources/user_credentials.csv
vars:
  in-json: test text
pipeline:
  test:
    - name: Echo example
      request: https://postman-echo.com/get?a={{a}}&b[0]={{b}}&b[1]={{bc}}
      method: GET
      repeats: 5
      delay: 2s
      vars:
        path1: world
        a: hello
        b: Ukraine
        bc: test
    - name: Echo example (POST)
      request: https://postman-echo.com/post
      method: POST
      headers:
        Content-Type: application/json
        Authorization: Bearer {{token}}
      vars:
        in-json: test text
        token: 43778f89af0267f02ab20d18
      body:
        raw: |-
          {
            "test": "test",
            "test1": {
              "key": "test text",
              "template": "{{in-json | capitalize}}",
              "array": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              "user": "{{user_credentials.username}}"
            }
          }
      capture:
        - json: '$.data.test1.key'
          as: key_value
          on:
            - assert:
                equal:
                  var: token
            - assert:
                equal:
                  value: 'value'
                message: 'Value must equal to "value"'
            - assert:
                message: 'Value must be equal to in-json variable'
                equal:
                  var: 'in-json'
            - assert:
                notequal:
                  value: 2
                message: Value must not be equal to 2
    - name: Echo example 2 (POST)
      request: http://localhost:5555/post
      method: POST
      headers:
        Content-Type: application/json
      body:
        json:
          test: test
          test1:
            key: value
            array: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    - name: Echo example 3 (POST, Json from file)
      request: https://postman-echo.com/post
      method: POST
      delay: 300ms
      headers:
        Content-Type: application/json
      vars:
        in-json: test text
        token: 43778f89af0267f02ab20d18
      body:
        uri: file://./resources/example_body.json
    - name: Local echo test
      request: http://localhost:65520/test
      method: POST
    - name: Non-standard method
      request: http://localhost:5555/test
      method: LIST
