name: Example
collect: mongodb://root:test123@localhost:27017
pipeline:
  test:
    - name: Echo example
      request: https://postman-echo.com/get?a={{a}}&b[0]={{b}}&b[1]={{bc}}
      method: GET
      vars:
        path1: world
        a: hello
        b: Ukraine
        bc: test
      before:
        js:
          uri: file://./scripts/before1.js
      after:
        js:
          code: |-
            "use strict";
            ctx.assert(ctx.response.status === 200);
    - name: Echo example (POST)
      request: https://postman-echo.com/post
      method: POST
      headers:
        Content-Type: application/json
        Authorization: Bearer {{token}}
      vars:
        in-json: test text
        token: 43778f89af0267f02ab20d18
      body:
        raw: |-
          {
            "test": "test",
            "test1": {
              "key": "value",
              "template": "{{in-json | capitalize}}"
              "array": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
            }
          }
      capture:
        json: '$.request'
    - name: Echo example 2 (POST)
      request: http://localhost:5555/post
      method: POST
      headers:
        Content-Type: application/json
      body:
        json:
          test: test
          test1:
            key: value
            array: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      capture:
        json: '$.request'
    - name: Local echo test
      request: http://localhost:65520/test
      method: POST
    - name: Non-standatd method
      request: http://localhost:5555/test
      method: LIST
